services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=sngproject
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=eventmanager_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: