// This file was generated by Prisma, and assumes you have installed the following: This was generated by Gemini
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
    seed: "prisma/seed.js",
  }
});

//test 1 2 3
